---
spring:
  profiles: subject
words: I,You,He,She,It
server.port: ${PORT:${SERVER_PORT:0}}
eureka.client.serviceUrl.defaultZone: http://localhost:9094/eureka

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
server.port: ${PORT:${SERVER_PORT:0}}
eureka.client.serviceUrl.defaultZone: http://localhost:9094/eureka

---
spring:
  profiles: article
words: a,the
server.port: ${PORT:${SERVER_PORT:0}}
eureka.client.serviceUrl.defaultZone: http://localhost:9094/eureka

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server.port: ${PORT:${SERVER_PORT:0}}
eureka.client.serviceUrl.defaultZone: http://localhost:9094/eureka

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
server.port: ${PORT:${SERVER_PORT:0}}
eureka.client.serviceUrl.defaultZone: http://localhost:9094/eureka
