spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prasadgamini/SpringCloudLearn
          search-paths: ConfigData
server:
  port: 9090

# This controls which Actuator web endpoints are exposed.
# Ordinarily, only /actuator/health and /actuator/info are exposed,
# But we need to allow external parties to POST to /bus-refresh:
management.endpoints.web.exposure.include: health,info,bus-refresh